services:
  - type: web
    name: drivebackuppro-license
    env: docker
    plan: free
    healthCheckPath: /healthz
    envVars:
      - key: Admin-API-Key
        sync: false
      - key: PRIVATE_PEM
        sync: false
